### ISSUE TITLE
What about the diff editor?

### ISSUE THREAD

**Issue by kricsleo** [CodinGame/monaco-editor-wrapper#110]
Since it's recommended to use `createEditor` exposed by this library, not the `monaco.editor.create`. Does there exist something like `createDiffEditor` exposed? I can't find it, or should we use the `monaco.editor.createDiffEditor` when requiring a diff editor?

**Comment by CGNonofr** [comment]
The only things that `createEditor` is doing now is to check that the services are properly initialized and configure 2 specific extensions you probably don't need. Calling the functions from monaco.editor is fine for both

**Comment by kricsleo** [comment]
Thanks, I'll try it 👍

**Comment by CGNonofr** [comment]
Btw, I will rework those extension and probably remove the createEditor function very soon
