### ISSUE TITLE
Unable to use defineTheme to define a custom theme

### ISSUE THREAD

**Issue by jpdery** [CodinGame/monaco-editor-wrapper#119]
Hi,
I've been trying to define a custom theme for this editor, but unfortunately the "default" defineTheme function is not there anymore. Is there a way to create a custom theme ?

Thanks

**Comment by CGNonofr** [comment]
Are you trying to define a monaco/monarch theme, or a textmate/VSCode one? please add a bit of context

**Comment by jpdery** [comment]
I guess it's more of a monaco theme. 

Some background:
I was using the standard monaco (and I've built a theme with it) editor and I was unhappy with the syntax highlighting. Then I came across this package. The editor works fine, but now I'm trying to apply the colors from my previous monaco theme on this editor.

However, If it's only possible to use a textmate/VSCode theme, that's fine with me. I'm just looking for a way to change the default theme.

Many thanks

**Comment by CGNonofr** [comment]
> unfortunately the "default" defineTheme function is not there anymore

Not sure what you mean though, the function seems to be there

**Comment by CGNonofr** [comment]
I see

Unfortunately, the VSCode syntax highlighting (textmate) is really tied to the VScode theme services, so you can't use textmate with monaco themes, nor monarch with VSCode themes

**Comment by jpdery** [comment]
Ok,

Is there any documentation or example on how to customize themes with your editor ? I've been trying to find projects that uses your editor, and it seems that at some point there was a `defineVSCodeTheme` function. Is there still something similar ?

Thanks

**Comment by CGNonofr** [comment]
`defineVSCodeTheme` was removed indeed

You can register your theme using a VSsode extension, either by
- using VSCode defaut themes by importing `@codingame/monaco-vscode-theme-defaults-default-extension`
- importing the vsix of a VSCode extension using the rollup vsix loader
- creating the extension by hands, something like:
```typescript
import { ExtensionHostKind, registerExtension } from 'vscode/extensions'

const { registerFileUrl, whenReady, setAsDefaultApi } = registerExtension(
  {
    name: 'world',
    publisher: 'hello',
    version: '1.0.0',
    engines: {
      vscode: '*'
    },
    contributes: {
      themes: [
        {
          id: 'My Theme',
          label: 'My Theme',
          uiTheme: 'vs-dark',
          path: './my-theme.json'
        }
      ]
    }
  },
  ExtensionHostKind.LocalProcess
)

registerFileUrl(
  './my-theme.json',
  new URL('./path/of/the/theme/on/the/disk.json', import.meta.url).toString()
)
```

**Comment by jpdery** [comment]
Looks like this is exactly what I needed. Thank you very much!
