### ISSUE TITLE
Using the extensionHostWorker extension prevents the initializer from resolving.

### ISSUE THREAD

**Issue by jpdery** [CodinGame/monaco-editor-wrapper#120]
As soon as I add this import:

`import '@codingame/monaco-editor-wrapper/features/extensionHostWorker'`

The promise from the initializer function never resolves. Through the Inspector I can't seem to find anything related to the worker too.

Is there something specific that needs to be done in order to get this working ?

Thanks

**Comment by CGNonofr** [comment]
No error either in the console or in the network?

Otherwise please provide a simple reproduction repo

**Comment by jpdery** [comment]
You can close that. The issue was that I was using webpack's html-loader and it was conflicting with HTML files loaded in the extension.

Thanks
