### ISSUE TITLE
module not found error package path

### ISSUE THREAD

**Issue by souravdevking** [CodinGame/monaco-editor-wrapper#48]
![18 07 2022_01 21 26_REC](https://user-images.githubusercontent.com/109483287/179422549-e8007ff9-6b2b-4d91-9b66-64a42ec108e4.png)
how to solve this error ?

**Comment by CGNonofr** [comment]
The path was changed in the last versions, import `@codingame/monaco-editor-wrapper/features/jsonContribution`, I'll update the README
