### ISSUE TITLE
listcodeeditor is not a function

### ISSUE THREAD

**Issue by souravdevking** [CodinGame/monaco-editor-wrapper#50]
![19 07 2022_11 42 39_REC](https://user-images.githubusercontent.com/109483287/179678376-8e41506e-8763-4d51-8074-7d9977e0cafc.png)

How to solve this error ?

**Comment by CGNonofr** [comment]
this lib shouldn't be used with the official monaco-editor release but @codingame/monaco-editor instead

**Comment by souravdevking** [comment]
> this lib shouldn't be used with the official monaco-editor release but @codingame/monaco-editor instead

I am using @codingame/monaco-editor . even I uninstall the monaco-editor but still got this error.
