### ISSUE TITLE
Attempted import error: 'setSnippetSuggestSupport' is not exported

### ISSUE THREAD

**Issue by souporserious** [CodinGame/monaco-editor-wrapper#86]
Hello, I'm trying to use this library in a Next.js application, and receive the following error:

<img width="990" alt="image" src="https://user-images.githubusercontent.com/2762082/224606102-32779b50-1e26-4783-a8de-1b5f079b10e1.png">

[Codesandbox repro here](https://codesandbox.io/p/sandbox/elastic-bush-z67uw6?file=%2Fapp%2Fpage.tsx)

I've configured Webpack to load wasm files. Is there any additional configuration I might be missing? I tried configuring the Monaco Webpack plugin as well, but that didn't seem to make a difference.

**Comment by Rockenstien** [comment]
has this issue been resolved?

**Comment by souporserious** [comment]
Not to my knowledge, I was able to work around this issue by using the core [monaco-vscode-api](https://github.com/CodinGame/monaco-vscode-api) library [here](https://github.com/souporserious/next-monaco-vscode-api) though.

**Comment by CGNonofr** [comment]
I don't know why I missed that issue!

It's a known issue, the required code from vscode is treeshaked out of monaco-editor and there is no way to polyfill it from the outside

monaco-vscode-api exposes a webpack loader that polyfills it on the fly => https://github.com/CodinGame/monaco-vscode-api/blob/main/src/webpack-loader.ts (you can probably do something similar for nextjs)

I hope for https://github.com/microsoft/vscode/pull/156120 to being merged to fix that issue but I'm starting to lose hope
